name: Test through code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Confirmation
        run: |
          echo  "I am here at a local branch"
